name: 'dms-tag-to-release'
description: 'Creates a Github Release when a new git tag is pushed.'
inputs:
  token:
    description: 'Github API token to use for creating release'
    required: true
    default: '${{ github.token }}'
runs:
  using: 'node12'
  main: 'src/index.js'
branding:
  icon: 'github'
  color: 'blue'
